### ISSUE TITLE
Plex Playlists not loading Content - error [argument of type 'nonetype' is not iterable]

### ISSUE THREAD

**Issue by aLTeReGo-SWI** [music-assistant/support#2711]
### What version of Music Assistant has the issue?

 2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.7.1.b0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Most (not all) Plex playlists never produce any results and return the error 'argument of type 'NoneType' is not iterable'. Full debug Error text below.

2024-08-01 09:41:00.355 ERROR (MainThread) [music_assistant.webserver] Error handling message: CommandMessage(message_id=25, command='music/playlists/playlist_tracks', args={'item_id': '12', 'provider_instance_id_or_domain': 'library', 'force_refresh': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/webserver.py", line 352, in _run_handler
    result = [x async for x in result]
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/playlists.py", line 65, in tracks
    tracks = await self._get_provider_playlist_tracks(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/playlists.py", line 353, in _get_provider_playlist_tracks
    for item in await provider.get_playlist_tracks(item_id, page=page):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/plex/__init__.py", line 895, in get_playlist_tracks
    if track := await self._parse_track(plex_track):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/plex/__init__.py", line 729, in _parse_track
    track.album = self._get_item_mapping(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/plex/__init__.py", line 428, in _get_item_mapping
    name, version = parse_title_and_version(name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/common/helpers/util.py", line 85, in parse_title_and_version
    if splitter in title:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

### How to reproduce

1. Click 'Music Assistant' from Home Assistant's left navigation pane
2. Click 'Playlists' from the bottom Music Assistant panel
3. Select a Playlist

### Music Providers

Plex

### Player Providers

UPnP/DLNA Player provider

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16487513/music-assistant.log)

### What version of Home Assistant Core are your running

2024.7.4

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Please follow the template instructions and replace the pasted log excerpt with an attached full log.

**Comment by aLTeReGo-SWI** [comment]
@OzGav log file uploaded

**Comment by OzGav** [comment]
Sorry but that is not the full log. You need to get it from the MA settings

**Comment by aLTeReGo-SWI** [comment]
@OzGav, apologies for that. Let's try that again. New (hopefully correct) logs uploaded

**Comment by OzGav** [comment]
@aLTeReGo-SWI Looking at this again. Firstly you have attached the log with DEBUG enabled. We ask you do not do this unless requested. Can you update to the latest version of MA, get this error to occur and then attach the logs WITHOUT debug enabled.

I do note that you have just about every provider enabled. Do you actually use all of those? If not then you should remove the ones you don't use.

**Comment by marcelveldt** [comment]
I can't reproduce this now on version 2.2.0 so either this is fixed in the series of bugfixes we did last releases or there is some trigger to indice the issue. Can you re-test once you upgraded to version 2.2.0 and let me know if this is still an issue ?

**Comment by aLTeReGo-SWI** [comment]
Updated to Music Assistant Server 2.2.2 using Music Assistant integration 2024.8.1

@OzGav the only provider(s) I have are shown in the screenshot below.

![2024-08-23_17-50-46](https://github.com/user-attachments/assets/062b546e-1d60-49ce-88b0-cd69367cab01)

Video of issue attached

https://github.com/user-attachments/assets/4e2c4ba2-eb24-4784-9466-da3e7698bd02

Logs collected after errors shown in video

[d5369777_music_assistant_2024-08-23T22-58-10.868Z.log](https://github.com/user-attachments/files/16734345/d5369777_music_assistant_2024-08-23T22-58-10.868Z.log)

I believe the issue may be related to a simple timeout or reaching some maximum size. The errors only appear on large playlists (hundreds of songs). Smaller playlists with only tens of tracks load just fine without error. If you're unable to reproduce the issue, I'm happy to share my Plex server with you so you can troubleshoot further.

**Comment by OzGav** [comment]
Not stale

**Comment by aLTeReGo-SWI** [comment]
@marcelveldt @OzGav This issue still persists on Home Assistant 2025.3.1 and Music Assistant Server 2.4.4. running against Plex v1.41.4.9463.

**Comment by OzGav** [comment]
Sorry Plex has no dedicated dev so this has not been looked at. If there is an update it will be posted here.

**Comment by cociweb** [comment]
I have similar behavior but with a different error message:
```
2025-03-24 02:43:46.997 ERROR (MainThread) [music_assistant.metadata] Error while updating metadata for library://playlist/55: expected string or bytes-like object, got 'NoneType'
2025-03-24 02:44:12.557 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/playlists/playlist_tracks: expected string or bytes-like object, got 'NoneType'
2025-03-24 02:44:16.884 ERROR (MainThread) [music_assistant.metadata] Error while updating metadata for library://playlist/56: expected string or bytes-like object, got 'NoneType'
2025-03-24 02:44:41.551 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/playlists/playlist_tracks: expected string or bytes-like object, got 'NoneType'
2025-03-24 02:45:00.004 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/playlists/playlist_tracks: expected string or bytes-like object, got 'NoneType'
```

some of the playlist works, but some of them throw this error.

**Comment by cociweb** [comment]
Maybe we should differentiate the issues, because we have 2 different error messages, but the behaviour is the same. my problem does not depend from the number of the items. @chicco-carone  I have a playlist with 110 item and the issue does not pops up and it loads, but I also have a playlist with 67 items and the issue exists with that.

**Comment by chicco-carone** [comment]
@cociweb are there any weird characters in the name of the playlist since that could possibly cause issues when parsing it from Plex that would result in a none type.

**Comment by cociweb** [comment]
I have all of the variations: a working playlist with and without special characters like `ú` and a non-working playlist with and without special characters like `-` `í`, so I don't think this is the root cause.

However....
The working playlists use only English charset (and without special characters like brackets, dash, comma, etc.) for the music filenames (and in their ID3 tags as well). Meanwhile, the non-working playlist has some (tons of...) music files with special characters in their filename and in the ID3 tags as well: `!` `.` `,` `()``-` `_` `[]` etc

**Comment by cociweb** [comment]
Now, I have some time to play with the filenames, titles, and Plex. I took a proper playlist and I've tried to make it bad without luck:
I've tried to add music with weird and special characters, but surprisingly, everything went well. Then, I've tried to change the ID3 title field to the same odd characters, but again, the playlist was OK. So, as of now, we should turn back to the desk. What else can be the root cause? I'm puzzled now about how to debug it. Maybe a temporary code modification would be useful to catch the wrong media file....

**Comment by cociweb** [comment]
https://github.com/music-assistant/server/pull/2182 resolves my issue, but I'm unsure about the resolution of the original ticket, since the code (and the error message lines/descriptions) changed a lot in the last 1 year... Perhaps the PR resolves it. A confirmation is also needed after the merge from @aLTeReGo-SWI.

**Comment by OzGav** [comment]
2.6.0b7 has been released. Please confirm this has been fixed

**Comment by OzGav** [comment]
Closing assumed fixed
