### ISSUE TITLE
music suddenly stop

### ISSUE THREAD

**Issue by kshexe** [music-assistant/support#2961]
### What version of Music Assistant has the issue?

2.2.5

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

music suddenly stops, but MA is playing and playing more than the end of the music
![Screenshot_20240924_090049_Samsung Internet](https://github.com/user-attachments/assets/0248f830-a91b-4982-b528-b5479fc263f3)

### How to reproduce

-

### Music Providers

local storage mp3 file 

### Player Providers

air play / two homepods in groups
![Screenshot_20240924_091240_Home Assistant](https://github.com/user-attachments/assets/6c742b21-4f28-4b04-a2bd-bc4513993851)

### Full log output

[music-assistant_240924.log](https://github.com/user-attachments/files/17106166/music-assistant_240924.log)

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Linux

**Comment by kshexe** [comment]
It worked well in early versions of 2.0, but it's been like this since it was recently updated around 2.2.

**Comment by OzGav** [comment]
@marcelveldt There are multiple different errors in the log??

**Comment by DrieWielRr** [comment]
I have the same issue, music sometimes stops at random but the player keeps going (and keeps going way beyond end of song):
![Screenshot 2024-10-18 155048](https://github.com/user-attachments/assets/4402c561-32d4-4854-91d0-2bed8dedfbc2)

MA logs show nothing and neither does the Snapcast-client both still believe they are playing a song that has ended +15 minutes ago.
We have music playing (via Spotify) nearly all day long when working from home and this happens daily, manually clicking "next track" usually fixed the problem and it starts playing the next track just fine until it cuts out again mid song and I have to select the next track again.

**Comment by DrieWielRr** [comment]
It just cutout again after <1h of playtime.

Log shows nothing:
2024-10-18 02:01:31.790 INFO (MainThread) [music_assistant] Starting Music Assistant Server (0b8864600b48456287ce1e316d39b158) version 2.2.7 - HA add-on: False - Safe mode: False
2024-10-18 02:01:31.799 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-10-18 02:01:32.114 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-10-18 02:01:32.183 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 6.1.1 with libsoxr support
2024-10-18 02:01:32.183 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8097 - base url: http://192.168.100.19:8097
2024-10-18 02:01:32.187 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://192.168.100.19:8095
2024-10-18 02:01:32.713 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv
2024-10-18 02:01:32.714 INFO (MainThread) [music_assistant] Loaded metadata provider The Audio DB
2024-10-18 02:01:32.714 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz
2024-10-18 02:01:32.754 INFO (MainThread) [music_assistant] Loaded plugin provider Home Assistant
2024-10-18 02:01:32.772 INFO (MainThread) [music_assistant.snapcast.snapserver] Starting builtin Snapserver...
2024-10-18 02:01:32.990 INFO (MainThread) [music_assistant.spotify] Successfully logged in to Spotify as Randy & Stephanie
2024-10-18 02:01:32.990 INFO (MainThread) [music_assistant] Loaded music provider Spotify
2024-10-18 02:01:36.563 INFO (MainThread) [music_assistant.snapcast] Started connection to Snapserver 127.0.0.1:1705
2024-10-18 02:01:36.563 INFO (MainThread) [music_assistant] Loaded player provider Snapcast
2024-10-18 02:01:36.565 INFO (MainThread) [music_assistant.players] Player registered: ma_0242ac120002/8d7f2affccc4
2024-10-18 02:01:50.962 INFO (MainThread) [music_assistant.music] Sync task for Spotify: Randy & Stephanie completed
2024-10-18 02:01:50.962 INFO (MainThread) [music_assistant.metadata] Starting metadata scanner
2024-10-18 02:01:50.968 INFO (MainThread) [music_assistant.metadata] Metadata scanner finished.
2024-10-18 05:01:40.574 INFO (MainThread) [music_assistant.music] Sync task for Spotify: Randy & Stephanie completed
2024-10-18 05:01:40.575 INFO (MainThread) [music_assistant.metadata] Starting metadata scanner
2024-10-18 05:01:40.580 INFO (MainThread) [music_assistant.metadata] Metadata scanner finished.
2024-10-18 08:02:06.220 INFO (MainThread) [music_assistant.music] Sync task for Spotify: Randy & Stephanie completed
2024-10-18 08:02:06.221 INFO (MainThread) [music_assistant.metadata] Starting metadata scanner
2024-10-18 08:02:06.225 INFO (MainThread) [music_assistant.metadata] Metadata scanner finished.
2024-10-18 11:01:40.215 INFO (MainThread) [music_assistant.music] Sync task for Spotify: Randy & Stephanie completed
2024-10-18 11:01:40.216 INFO (MainThread) [music_assistant.metadata] Starting metadata scanner
2024-10-18 11:01:40.221 INFO (MainThread) [music_assistant.metadata] Metadata scanner finished.
2024-10-18 11:45:36.405 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Beneden - crossfade: True
2024-10-18 12:03:11.212 INFO (MainThread) [music_assistant.spotify] Attempt 1/5 failed: Token expired
2024-10-18 12:03:11.213 INFO (MainThread) [music_assistant.spotify] Retrying in 0.1 seconds...
2024-10-18 13:55:17.680 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Beneden - crossfade: True
2024-10-18 14:02:06.207 INFO (MainThread) [music_assistant.music] Sync task for Spotify: Randy & Stephanie completed
2024-10-18 14:02:06.208 INFO (MainThread) [music_assistant.metadata] Starting metadata scanner
2024-10-18 14:02:06.213 INFO (MainThread) [music_assistant.metadata] Metadata scanner finished.
2024-10-18 15:52:21.018 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Beneden - crossfade: True
2024-10-18 15:52:22.730 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Beneden - crossfade: True


It seems to have happened on the end of the song this time during the crossfade, ill keep monitoring if it always happens during crossfade or also mid track.

**Comment by OzGav** [comment]
@DrieWielRr can you try with a different player type and see if you can reproduce.

**Comment by DrieWielRr** [comment]
> @DrieWielRr can you try with a different player type and see if you can reproduce.

What exactly do you mean, something else than Spotify, or a different client than spotcast-client?

**Comment by OzGav** [comment]
I meant different player but looking at your log you have posted in the wrong thread. This is a Spotify error https://github.com/music-assistant/hass-music-assistant/issues/2863 The OP is about local storage and AirPlay

**Comment by DrieWielRr** [comment]
> I meant different player but looking at your log you have posted in the wrong thread. This is a Spotify error #2863 The OP is about local storage and AirPlay

Ohh, my bad did not notice that.

**Comment by OzGav** [comment]
@kshexe Groups have been reworked in the beta. Can you try the beta and see if this has been fixed, You can install the beta server alongside the stable just don't have them running at the same time.

**Comment by kshexe** [comment]
[music-assistant1023.log](https://github.com/user-attachments/files/17486154/music-assistant1023.log)

The situation is similar. @OzGav

**Comment by OzGav** [comment]
OK lets wait until @marcelveldt can look at this one

**Comment by marcelveldt** [comment]
fixed in 2.3.0 rc 1

**Comment by OzGav** [comment]
2.3.0rc1 is released. Please test again

**Comment by kshexe** [comment]
@OzGav Now the song doesn't break, it stops on the player.
![스크린샷 2024-10-25 205416](https://github.com/user-attachments/assets/50291acd-8b55-4b82-b9de-f7648254bb01)
[music-assistant (1).log](https://github.com/user-attachments/files/17521635/music-assistant.1.log)

**Comment by OzGav** [comment]
@marcelveldt a lot of errors in the log?

**Comment by kshexe** [comment]
@OzGav I think it stops once 9-10 seconds before the end of the song.
[music-assistant1028.log](https://github.com/user-attachments/files/17535708/music-assistant1028.log)
![Screenshot_20241027_153635_Home Assistant](https://github.com/user-attachments/assets/f4aca43c-6421-4b31-9a9d-362b644b00ee)

**Comment by OzGav** [comment]
@marcelveldt there are still a ton of errors in the log?

**Comment by marcelveldt** [comment]
> @marcelveldt there are still a ton of errors in the log?

The queue/player name is using non-ascii characters which makes the imageproxy crash. I will have to look into that.

**Comment by flexmatics** [comment]
Hey,

It does look like I have the same issue - songs randomly stop with 7-10 sec remaining to until the end of the song. See logs - a) music started at 18:54, music stopped at 18:58 (no errors), then at 19:01 there is an error. At 19:01 there was also 0.5-1 sec sound from speakers of this previous song.

> 2024-11-06 18:54:31.106 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue living_room - crossfade: False
2024-11-06 19:01:42.677 ERROR (MainThread) [ffmpeg.2412] Stream error: TimeoutError

MA server: 2.4.0b4
MA integration: 2024.11.1
Spotify used (with Client ID)
Player: Slimproto player

Should I raise a new issue, or can track here? any other info to be provided?

**Comment by lwsrbrts** [comment]
I reverted to 2.2.7 due to a random stopping issue affecting me since 2.3.0.

I am playing to a Google Cast group with 3 x Chromecast Audio devices in. I am playing long "tracks" which are basically podcasts of music (DJ mixes). Unfortunately I can't extract the errors from the log as it has since disappeared post revert but I do recall there being an error referring to `cmd_power` and there additionally being a notification that the queue had finished. It hadn't since the track was often barely 1-2 minutes in before the error occurred.

I'll attempt to update to 2.3.2 or 2.4.0 when that's released and see if I still see the issue.

**Comment by lor74** [comment]
Hi same issue with Airplay
please find attached the full log
[music-assistant.log](https://github.com/user-attachments/files/17789302/music-assistant.log)

Current MA version: 2.4.0b5
HA Core 2024.11.2
HA Supervisor 2024.11.2
HA Operating System 13.2
HA Frontend 20241106.2

```

2024-11-17 08:28:57.496 DEBUG (MainThread) [music_assistant.audio.media_stream] stream finished (with code 0) for spotify://track/6m6nCDeDNpfW78utlH3Qte - seconds streamed: 146.17333333333335
2024-11-17 08:28:58.613 DEBUG (MainThread) [music_assistant.streams] Finished Streaming queue track: spotify://track/6m6nCDeDNpfW78utlH3Qte (Hank Shizzoe - California) on queue AirPlayGroup
2024-11-17 08:28:58.613 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for spotify://track/4ltSwgfNcUSl42nu0YKd3L
2024-11-17 08:28:58.624 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for spotify://track/4ltSwgfNcUSl42nu0YKd3L in 10 milliseconds
2024-11-17 08:28:58.625 DEBUG (MainThread) [music_assistant.streams] Start Streaming queue track: spotify://track/4ltSwgfNcUSl42nu0YKd3L (Hank Shizzoe/Loose Gravel - Handmade Love (Live)) for queue AirPlayGroup
2024-11-17 08:28:58.625 DEBUG (MainThread) [music_assistant.audio.media_stream] start media stream for: spotify://track/4ltSwgfNcUSl42nu0YKd3L
2024-11-17 08:29:43.293 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 377, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.InvalidURLError: 400, message:
  Invalid char in url query:

    b'GET /imageproxy?path=https%253A//i.scdn.co/image/ab67616d0000b273a1f9e983ad47bb292dfbd6ea&provider=spotify&size=500&fmt=jp\x07 HTTP/1.0'
```
I don't know if is the same problem but here #2952  @OzGav  closed the issue reverting here. If is not the "right place" I can open a new issue.

Thanks fpr support

**Comment by niteguide** [comment]
Just for reference: in #3131 I describe the same kind of issue for other music providers (Spotify, Tidal).

**Comment by kshexe** [comment]
I was using version 2.2.2 2024.10.1 because this issue was not resolved. I didn't see the problem with that version. 2024.10.1 became unavailable and faced the problem again as homeassistant became 2024.12.0. When I looked it up today, it seems that there must be a local that occurs, so I would like to deliver mp3. (I want to give it to you personally because I think there will be a copyright issue.)
[music-assistant_241206.log](https://github.com/user-attachments/files/18032445/music-assistant_241206.log)

**Comment by flexmatics** [comment]
Just thought I'd share - I've disabled 'Enable queue flow mode' for my slimproto players and the issues with stopping music disappeared (or at least I do not notice anymore). Referring to my comment [here](https://github.com/music-assistant/hass-music-assistant/issues/2961#issuecomment-2460332228)

**Comment by kshexe** [comment]
@flexmatics I play on MA without a separate player and I don't know where Enable queue flow mode is. Is there a way to turn it off in MA as well?

**Comment by lwsrbrts** [comment]
@kshexe On the Settings page of your player.
![image](https://github.com/user-attachments/assets/365fc86b-5888-477e-a9d8-0e000420db8c)
Enable or disable as you need.
![image](https://github.com/user-attachments/assets/25e8ebc0-f293-44f9-a628-8fb655dfb8c0)

**Comment by kshexe** [comment]
@lwsrbrts I use the homeepot group, but I don't have that menu.
![generic](https://github.com/user-attachments/assets/ecb5449f-4f6e-4fe9-9f90-d625888cdf17)

**Comment by OzGav** [comment]
Queue flow mode would be enabled or disabled on the individual players not the group

**Comment by kshexe** [comment]
Not even in individual players. @OzGav 
![generic2](https://github.com/user-attachments/assets/fa8abe45-3170-4f82-9c8b-26c0c4748edb)

**Comment by OzGav** [comment]
Some players have this on by default and it cannot be disabled. If you have any more questions about this open a Q&A or ask on Discord as this is drifting away from this issue report.

**Comment by kshexe** [comment]
@OzGav I don't want to do anything about this mode, I want to improve the singing stop. I've been suffering for too long.

**Comment by kshexe** [comment]
@OzGav Is there a way out? Should I change the player name to English? Does anyone else happen with that mp3?

**Comment by OzGav** [comment]
Your original report said it occurs with homepods in groups. Have you tried an individual homepod?

**Comment by kshexe** [comment]
@OzGav It stops regardless of whether it's a group or an individual.

**Comment by kshexe** [comment]
@OzGav The same error occurs whether it is an individual or a group.
[music-assistant_241225.log](https://github.com/user-attachments/files/18243181/music-assistant_241225.log)
![1111](https://github.com/user-attachments/assets/e855303d-bcb0-4983-85f0-8ae7985bfd23)
![222](https://github.com/user-attachments/assets/1a52b1a2-edfe-4487-96e8-c9f939ff0910)

**Comment by OzGav** [comment]
Ok thanks. This will get looked at again in due course.

**Comment by mwaterbu** [comment]
> Should I change the player name to English? Does anyone else happen with that mp3?

I have also had this happen when playing from local files, and my player names are in latin script. I will try to remember to get a log file next time.

**Comment by OzGav** [comment]
We have identified a problem with ffmpeg. An update has been shipped in 2.4.0b14. Please report if this has been fixed

**Comment by kshexe** [comment]
[music-assistant0115.log](https://github.com/user-attachments/files/18418719/music-assistant0115.log)
2025-01-15 12:19:44.548 WARNING (MainThread) [music_assistant.audio] Could not determine integrated loudness of filesystem_local--jpAh26xm://track/콩순이/콩순이의 율동교실 9/콩순이 아춰아뜨송.mp3 - received empty value
2025-01-15 12:19:50.117 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2025-01-15 12:19:55.166 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue 거실홈팟1 - crossfade: False
2025-01-15 12:19:56.768 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue 거실홈팟1 - crossfade: False
2025-01-15 12:20:05.067 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue 거실홈팟1 - crossfade: False
2025-01-15 12:20:09.888 WARNING (MainThread) [music_assistant.webserver] Disconnected: Received non-Text message.
2025-01-15 12:20:32.736 WARNING (MainThread) [asyncio] child process pid 558 exit status already read:  will report returncode 255

I ran with joy, but I can't play it

**Comment by OzGav** [comment]
That is a DIFFERENT problem. There is something wrong with that track. Try something different.

**Comment by kshexe** [comment]
@OzGav Everything in the local area is like that.
It works well where it's not beta.

**Comment by OzGav** [comment]
OK this is a different problem to what you were originally reporting. Let me ask about that.

**Comment by marcelveldt** [comment]
Current beta (b14) has an issue with airplay, we're looking into it.

**Comment by badewanne1234** [comment]
I am on 2.3.6 (the latest official version) and I see you have found an issue with ffmpeg - just for complettness, I have the same issue when playing from local filesystem (remote share). FYI - I also cannot enable "queue flow" for this player (its from the Home-Assistant.
As you can see below, music stops all of a sudden - and sometimes (but not everytime), it starts playing again without me touching anything. In the example below, after 2mins.

```
2025-01-15 06:46:29.076 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Heos Kitchen - crossfade: False
2025-01-15 06:50:12.098 ERROR (MainThread) [ffmpeg.34] No audio data received from source after timeout
2025-01-15 06:50:12.204 ERROR (MainThread) [ffmpeg.40] No audio data received from source after timeout
2025-01-15 06:50:12.311 ERROR (MainThread) [ffmpeg.46] No audio data received from source after timeout
2025-01-15 06:50:12.972 ERROR (MainThread) [ffmpeg.52] No audio data received from source after timeout
2025-01-15 06:50:13.140 ERROR (MainThread) [ffmpeg.64] No audio data received from source after timeout
2025-01-15 06:50:13.447 ERROR (MainThread) [ffmpeg.70] No audio data received from source after timeout
2025-01-15 06:52:29.950 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Heos Kitchen - crossfade: False
```

**Comment by OzGav** [comment]
@badewanne1234 you need to try beta15+

**Comment by badewanne1234** [comment]
thank you I will test beta and let you know about any improvements

**Comment by badewanne1234** [comment]
Update: I was listening to music about 2hrs with no issues. 
Then, I again started listening to music and after approx 10mins, I had a 5sec stop. It stopped, then started again very quickly. When I had this issue with 2.3.6, it would stop for 2mins, then starting again with playback, or not starting playback again at all.

**Comment by marcelveldt** [comment]
That is most likely a different issue and I will need to see the full log (download the logfile from the settings menu and attach it here).

We have multiple confirmations that the original issue is resolved.

**Comment by badewanne1234** [comment]
That would be awesome!
correct, no warning in the logs, however at the moment I only have standard logging set.
What loglevel is required and for which controller to (potentially) catch it?

**Comment by kshexe** [comment]
I tried it yesterday and today, and it's fine. It sounds good.

**Comment by OzGav** [comment]
As the original issue is fixed this will be closed. @badewanne1234 please open a new issue when you narrow down the problem. Logs are required and repeatable steps.
