### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by duhow** [music-assistant/support#3159]
### What version of Music Assistant has the issue?

2.4.0b5

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

```python
DEBUG [music_assistant_client] Provider hass_players--wsay7fZB is not available

Error while setting up mass platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/mass/media_player.py", line 147, in async_setup_entry
    mass_players.append(MusicAssistantPlayer(mass, player.player_id))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/media_player.py", line 204, in __init__
    super().__init__(mass, player_id)
  File "/config/custom_components/mass/entity.py", line 34, in __init__
    manufacturer=self.player.device_info.manufacturer or provider.name,
                                                         ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
```

https://github.com/music-assistant/hass-music-assistant/blob/main/custom_components/mass/entity.py#L34

### How to reproduce

Having the `provider` **Home Assistant MediaPlayers** with some entities offline generates above exception.

### Music Providers

N/A

### Player Providers

* `Home Assistant MediaPlayers`

### What version of Home Assistant Core are your running

2024.11.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
With the volume of requests for assistance on here, Discord and the HA forums we need people to provide the information requested in a concise manner. You are getting this standard response because you have not supplied the information requested in the troubleshooting docs or in the issue report template and we are unable to quickly pinpoint the problem. Please review and supply the requested information for a more timely response to your problem. Thanks for your understanding.

**Comment by duhow** [comment]
I think the error is pretty straight forward, I cannot seem to provide any additional information other than "this appears when starting Home Assistant".

**Comment by OzGav** [comment]
The troubleshooting docs are pretty clear that you need to detail what you have tried to resolve this that hasn't worked. You also aren't running the latest version of the server or the integration. You need to help us to help you.

**Comment by duhow** [comment]
Updated description.

**Comment by OzGav** [comment]
Switch to the core integration and advise if this is still an issue. Also you still haven’t provided all of the information requested in the docs.

**Comment by OzGav** [comment]
This will be closed soon due to no follow up
