### ISSUE TITLE
Spotify Playlist timing out

### ISSUE THREAD

**Issue by itkama** [music-assistant/support#3222]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.11.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I'm playing a 5 hour long spotify playlist (Rock Rotation). After a while (in the logs below after around 1 hour) the music just stops.
I can start another playlist or the same one right away and music is playing again. 

### How to reproduce

Since the time it takes to time out varies, it's hard to give clear steps on how to reproduce this.

### Music Providers

Spotify, I currently don't have other music providers available

### Player Providers

Snapcast on a Raspberry Pi with a Hifiberry Hat

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17894446/music-assistant.log)
Not sure how many times it is in the logs, but around 16:33:12 was when it stopped playing music. 

### Additional information

Playback is being instigated via service call from HA that has a playlist URI in it ("spotify://playlist/37i9dQZF1DWZJhOVGWqUKF"). Selecting a playlist manually via the UI usually results in the same problem.

### What version of Home Assistant Core are your running

2024.11.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
The issue template says this

> Please do NOT use debug logging unless asked to do so.

and you have used verbose which is worse? Having verbose on can cause timing issues.

**Comment by relianteng** [comment]
My Spotify playlists also stop after a while; usually less then 30 minutes. This is what I see in the logs before my streams end. Any solutions?

`2024-11-27 14:03:48.214 WARNING
(MainThread)
[music_assistant.webserver]
Disconnected: Received non-Text message.
2024-11-27 14:15:52.472 ERROR
(MainThread) [ffmpeg.614] Stream error: TimeoutError `

**Comment by jojo141185** [comment]
I have the same problem and get the exactly the same warning in debug log.
 After the Song "Mariah Carey - All I Want for Christmas Is You" the playback stopped although more songs are queued on the player.

> 2024-11-30 12:03:19.930 DEBUG (MainThread) [snapcast.control.server
> ] stream MusicAssistant--5001 updated
> 2024-11-30 12:06:46.770 DEBUG (MainThread) [music_assistant.audio.m
> edia_stream] stream finished (with code 0) for spotify--SsGzbM76://
> track/2TE4xW3ImvpltVU0cPcKUn - seconds streamed: 220.16
> 2024-11-30 12:06:48.210 DEBUG (MainThread) [music_assistant.streams
> ] Finished Streaming queue track: spotify--SsGzbM76://track/2TE4xW3
> ImvpltVU0cPcKUn (Shakin' Stevens - Merry Christmas Everyone) on que
> ue Wohnzimmer
> 2024-11-30 12:06:48.210 DEBUG (MainThread) [music_assistant.audio]
> Getting streamdetails for spotify://track/0bYg9bo50gSsH3LtXe2SQn
> 2024-11-30 12:06:48.219 DEBUG (MainThread) [music_assistant.audio]
> retrieved streamdetails for spotify://track/0bYg9bo50gSsH3LtXe2SQn
> in 8 milliseconds
> 2024-11-30 12:06:48.219 DEBUG (MainThread) [music_assistant.streams
> ] Start Streaming queue track: spotify--SsGzbM76://track/0bYg9bo50g
> SsH3LtXe2SQn (Mariah Carey - All I Want for Christmas Is You) for q
> ueue Wohnzimmer
> 2024-11-30 12:06:48.219 DEBUG (MainThread) [music_assistant.audio.m
> edia_stream] start media stream for: spotify--SsGzbM76://track/0bYg
> 9bo50gSsH3LtXe2SQn
> 2024-11-30 12:09:21.766 WARNING (MainThread) [music_assistant.webse
> rver] Disconnected: Received non-Text message.
> 2024-11-30 12:09:21.767 DEBUG (MainThread) [aiohttp.server] Ignored
>  premature client disconnection.
> 2024-11-30 12:11:54.089 DEBUG (MainThread) [snapcast.control.server
> ] stream MusicAssistant--5001 updated
> 2024-11-30 12:12:03.033 DEBUG (MainThread) [aiohttp.server] Ignored
>  premature client disconnection 2

**Comment by OzGav** [comment]
These seem to be client problems as two of the reporters are using Snapcast and the log indicates a client disconnection. Thoughts @SantiagoSotoC

**Comment by OzGav** [comment]
In the meantime reporters using Spotify please add radiobrowser if you don’t have any other music providers and find a radio station you like and start streaming that and see if you have any issues.

**Comment by OzGav** [comment]
Might also be related to https://github.com/music-assistant/hass-music-assistant/issues/3257

**Comment by SantiagoSotoC** [comment]
I had not seen that error before. 
I'm going to have to find another way to send the audio to the snapserver, ffmpeg is not intended as a player. And it's used that way, plus it doesn't support snapcast's 24 bit format. 
Having a client disconnect shouldn't cause a problem. The audio is not sent to each client, but a stream received by the snapserver.

**Comment by OzGav** [comment]
Keeping open for now

**Comment by tlskinneriv** [comment]
I experience a similar problem with Spotify as the streaming provider and Snapcast as the payer provider. It seems to play a song nearly to the end, then goes silent and the elapsed time bar continues to move and even go past the elapsed time of the song.

Example log messages at the time this happens:

```
2024-12-29 19:38:56.768 WARNING (MainThread) [music_assistant.audio.media_stream] Stream error on spotify--bHRW5ezK://track/5WSrKZAdS4mkPEBpZPCZR9
2024-12-29 19:38:56.768 ERROR (MainThread) [ffmpeg.22248] Stream error: TimeoutError
``` 

For me, this isn't any song in particular and is not predictable when it will happen (e.g. yesterday I could only get a couple hours at a time and today I got 7 or so hours before it happened again).

**Comment by OzGav** [comment]
Is everyone that has reported this using their own ClientID with Spotify?

**Comment by tlskinneriv** [comment]
> Is everyone that has reported this using their own ClientID with Spotify?

For my particular issue, I've seen it with both having one and not having one. Setting a ClientID was a troubleshooting step for me, and I've left it in place since. I have two Spotify accounts loaded, and this happens to playlists from either of them.

**Comment by itkama** [comment]
> Is everyone that has reported this using their own ClientID with Spotify?

Using my own client ID. Only one Spotify account.

**Comment by relianteng** [comment]
I am also using my own ClientID

**Comment by OzGav** [comment]
Thanks this is being looked at

**Comment by OzGav** [comment]
beta 17 has been released with a fix for this. Please advise if this is resolved

**Comment by D3B453R** [comment]
> beta 17 has been released with a fix for this. Please advise if this is resolved

I'm currently running the nightly build on a freshly installed system (today) to test it. And as far as I can tell the issue is gone for me, thanks :)

**Comment by relianteng** [comment]
Beta 17 was pretty good but I received an `ERROR (MainThread) [ffmpeg.1470] Stream error: TimeoutError ` after 3 hours of playing music. I updated to beta 18 and have been able to play music 8.5 hours today before receiving the timeout error. Seems like the issue is addressed.

**Comment by OzGav** [comment]
@itkama This will be closed soon assuming fixed

**Comment by OzGav** [comment]
@itkama you can run the beta server in parallel to test it? https://www.music-assistant.io/release/

**Comment by itkama** [comment]
Wouldn't I need to change all my automations where I currently use the mediaplayer from MA? And how does the service call choose which server it tells to play the music?

**Comment by OzGav** [comment]
I’m just suggesting you spin it up temporarily and see if the timeout error is fixed

**Comment by jojo141185** [comment]
I had the opportunity to run a small test with server version 2.04.0b18 today. 
In the morning, a Spotify playlist with approximately 50 tracks played through successfully. In the afternoon (other playlist, different Snapcast client), playback stopped after 36 tracks. 
In the log, I encountered an ffmpeg timeout error, similar to what user relianteng [mentioned above](https://github.com/music-assistant/support/issues/3222#issuecomment-2601138751).

<details>
  <summary><i>Log excerpt of MusicAssistant server</i></summary>
<code>2025-01-22 13:41:24.913 DEBUG (MainThread) [music_assistant.streams] Finished Streaming queue track: spotify://track/5ZgsblCqzc7oR3y2aUKR6O (Dorfrocker/Kings of Günter - Spaghetti Polonaise) on queue orangepi-wohnzimmer
2025-01-22 13:41:24.914 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for spotify://track/4DvWYFv3kYm9U8pJ5gQwn1
2025-01-22 13:41:24.921 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for spotify://track/4DvWYFv3kYm9U8pJ5gQwn1 in 6 milliseconds
2025-01-22 13:41:24.922 INFO (MainThread) [music_assistant.streams] Start Streaming queue track: spotify://track/4DvWYFv3kYm9U8pJ5gQwn1 (Kreisligalegende/Honk!/Thekensportlerz - Dorflove) for queue orangepi-wohnzimmer
2025-01-22 13:41:24.922 DEBUG (MainThread) [music_assistant.player_queues] PlayerQueue orangepi-wohnzimmer loaded item 4852d9bb10a148609cb35e5d1de7ad60 in buffer
2025-01-22 13:41:24.930 DEBUG (MainThread) [music_assistant.audio.media_stream] Started media stream for spotify://track/4DvWYFv3kYm9U8pJ5gQwn1 - using streamtype: custom - volume normalization: dynamic - pcm format: f32le - ffmpeg PID: 1795
2025-01-22 13:41:39.288 DEBUG (MainThread) [music_assistant.player_queues] PlayerQueue orangepi-wohnzimmer played item spotify://track/5ZgsblCqzc7oR3y2aUKR6O for 177 seconds - fully_played: True - progress: 177.8705017534885
2025-01-22 13:42:39.953 DEBUG (MainThread) [snapcast.control.server] stream MusicAssistant--5055 updated
2025-01-22 13:46:24.936 DEBUG (MainThread) [music_assistant.audio.media_stream] stream aborted (with code 183) for spotify://track/4DvWYFv3kYm9U8pJ5gQwn1 - seconds streamed: 0 

2025-01-22 13:46:24.936 ERROR (MainThread) [ffmpeg.1101] Stream error: TimeoutError
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/streams.py", line 669, in get_flow_stream
    async for chunk in self.get_media_stream(
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/streams.py", line 870, in get_media_stream
    async for chunk in get_media_stream(
  File "/app/venv/lib/python3.12/site-packages/music_assistant/helpers/audio.py", line 387, in get_media_stream
    async for chunk in ffmpeg_proc.iter_chunked(pcm_format.pcm_sample_size):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/helpers/process.py", line 121, in iter_chunked
    chunk = await self.readexactly(n)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/helpers/process.py", line 139, in readexactly
    return await self.proc.stdout.readexactly(n)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 752, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 545, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/helpers/ffmpeg.py", line 145, in _feed_stdin
    async for chunk in TimedAsyncGenerator(self.audio_input, timeout=300):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/helpers/util.py", line 624, in __anext__
    result = await asyncio.wait_for(self._iterator.__anext__(), int(timeout))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
2025-01-22 13:46:24.939 DEBUG (MainThread) [snapcast.control.server] stream MusicAssistant--5055 updated
2025-01-22 13:46:24.943 DEBUG (MainThread) [music_assistant.snapcast] Finished streaming to tcp://server.leo.lan:5055
2025-01-22 13:46:25.000 DEBUG (MainThread) [snapcast.control.server] stream MusicAssistant--5055 updated
2025-01-22 13:46:25.196 DEBUG (MainThread) [music_assistant.player_queues] PlayerQueue orangepi-wohnzimmer played item spotify://track/4DvWYFv3kYm9U8pJ5gQwn1 for 286 seconds - fully_played: True - progress: 286.35410824712017
2025-01-22 13:46:25.203 DEBUG (MainThread) [snapcast.control.server] stream found: Snapstream (TCPStream)
</code>
</details>

**Comment by OzGav** [comment]
This issue is assumed fixed in 2.4.0rc4 or later. If this is not the case then please advise ASAP
