### ISSUE TITLE
mass.play_media action fails when radio_mode:true with Spotify

### ISSUE THREAD

**Issue by 1joneselliot** [music-assistant/support#3241]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When using the action "mass.play_media" in a Home Assistant automation or script, the action fails with error "Error: recommendations not found", only when the "radio_mode" parameter is set to "true". When it is changed to "false", the action works as expected. No difference in behavior for grouped/ungrouped players. This was working without issue in my automations since before 2024.11.4.

Radio mode seems to be enabled by default in the web player (I couldn't find a way to turn it on/off) and works as expected.

### How to reproduce

Create a Home Assistant automation that uses the mass.play_media action with radio mode enabled. Run the automation. Observe the "Error: recommendations not found" error. 

### Music Providers

Spotify
I have no other providers

### Player Providers

Google Nest Mini, Google Nest Hub, Samsung TV
Issue occurs on all players

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17951378/music-assistant.log)

### Additional information

Have tried rebooting HA as well as reloading MASS, re-registering Spotify, etc. 

### What version of Home Assistant Core are your running

2024.11.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Confirmed. Will be looked at soon.

**Comment by uneatensoup** [comment]
Hi, would it be easy to help fix this issue, or is it more advanced? I’m primarily a scripter and can understand code, but I’m not a full developer. I’d really like to fix it because it’s quite annoying.

**Comment by lor74** [comment]
The issue is present also using the new integration music_assistant.
If is not used the Client ID from Spotify App (leaving blank when create authentication on spotify provider) radio mode works... but there is the well known throttling issue.

Using this simple script

```
action: music_assistant.play_media
data:
  media_id: Van Morrison
  media_type: artist
  radio_mode: true
target:
  device_id: caba6b5a7a109e62be346484957a84f9
```

In the logs attached

```
[music-assistant.log](https://github.com/user-attachments/files/18266398/music-assistant.log)
```

you will find that when I do not use Client ID (having throttling ) the rado mode is working

```
2024-12-28 12:19:55.234 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue airport express di lorenzo (Airplay) - crossfade: False
2024-12-28 12:19:55.234 DEBUG (MainThread) [music_assistant.streams] Start Streaming queue track: spotify://track/4beWEVoUbjSziAFPy8voaF (Van Morrison - Someone Like You) for queue airport express di lorenzo (Airplay)
```

Using Client ID I got this error

```
2024-12-28 12:22:04.115 ERROR (MainThread) [music_assistant.webserver] Error handling message: CommandMessage(message_id='0cf2a59e37444ecc94f911b1f2cf4727', command='player_queues/play_media', args={'queue_id': 'apac7f3ee81fe7', 'media': ['library://artist/201'], 'option': None, 'radio_mode': True, 'start_item': None})
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/webserver.py", line 361, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/player_queues.py", line 419, in play_media
    tracks = await self._get_radio_tracks(queue_id=queue_id, is_initial_radio_mode=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/player_queues.py", line 1454, in _get_radio_tracks
    for track in await track_ctrl.get_provider_similar_tracks(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/media/tracks.py", line 395, in get_provider_similar_tracks
    return await prov.get_similar_tracks(prov_track_id=prov_mapping.item_id, limit=limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/spotify/__init__.py", line 537, in get_similar_tracks
    items = await self._get_data(endpoint, seed_tracks=prov_track_id, limit=limit)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/helpers/throttle_retry.py", line 119, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/spotify/__init__.py", line 903, in _get_data
    raise MediaNotFoundError(f"{endpoint} not found")
music_assistant_models.errors.MediaNotFoundError: recommendations not found
```

The issue is not related to OS since I am using Rasperry.

**Comment by lor74** [comment]
Just another detail... I noticed that my spotify app dashboard show that no API calls were made

![Screenshot 2024-12-29 alle 09 14 11](https://github.com/user-attachments/assets/1a33d3ac-587f-41a5-bfde-eda06488a3b4)

Wich is the difference using my client ID and using the default method?

**Comment by OzGav** [comment]
Apparently Spotify has changed their API to make things difficult. As you have seen recommendations is not working when using a personal clientid. However, if you don’t use a personal clientid then you will find initiating playback is slower and requests may timeout.

This may end up being a limitation but we will get back to you.

**Comment by lor74** [comment]
Thanks for details.... and thanks for try to find a solution to this Spotify change.

**Comment by OzGav** [comment]
At this point the choice is to go with another provider.

**Comment by lor74** [comment]
I have quobuz as another provider for lossless... and it doesn't support radiomode. I have been using Spotify for a long time ... I have a family plan... and the algorithm for music suggestions is very good... Tdal supports radio mode too right?
It is something to think about

**Comment by OzGav** [comment]
Closing as this is outside of the projects control
