### ISSUE TITLE
Music Stops with Spotify and LMS 

### ISSUE THREAD

**Issue by Haloto** [music-assistant/support#3272]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

Official 

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

First of all I want to thank the the Team for this amazing program. Thank you for all your effort and work. The problem I am facing is, that my music stops towards the end of a song, not finishing the song and not playing the next song in the queue. It is similar to other issues I have seen mentioned here, only that it stops with the progress bar jumping two seconds back and then counting up in a loop instead of continuing to count further than the duration of the song. 

### How to reproduce

Play music using spotify and LMS clients (LouderESP32 running squeezelite esp32). Eventually the music will stop. 

I found a way to reliably reproduce this error, even though it might not be reproducable for other people. I have a playlist in which, if I repeat the one specific song the music stops reliably at the end of the following song. This is just to say that it can be reliably reproduced and is not due to a network iussue. 

Edit: I played with it a bit more and initially playing this song directly lead to the described behaviour. However after a while the behaviour stopped. Here is song: Insect Nightmares from The Lillingtons and the Album Stella Sapiente. 

### Music Providers

Spotify

### Player Providers

LMS clients (LouderESP32 running squeezelite ESP32, newest version)

### Full log output

[MA Log Info Level.txt](https://github.com/user-attachments/files/18041638/MA.Log.Info.Level.txt)
At the bottom you can see three times the line: "[ffmpeg.113] Stream error: TimeoutError" which corresponds to the times I reproduced the issue on purpose. 

I reproduced the issue with debug logs enabled and recieved the following at that ppoint in the logs: 
[MA Log Debug Level.txt](https://github.com/user-attachments/files/18041798/MA.Log.Debug.Level.txt)
Here you can also see the two songs which are played, however, they are in a personal playlist and I dont know if others are able to reproduce the isssue this way.

### Additional information

As others have mentioned I never had that issue prior to the refactoring of the sync groups which happend in 2.3 I think. However I believe I updated from 2.2.2 directly to 2.3.

### What version of Home Assistant Core are your running

2024.12.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by Haloto** [comment]
Thank you for your answer :) 

While I had the chance to replicate the problem I tried it with and without the "force mp3" option. It did, however create the same result. 

I managed to try the snapcast browser option you recommended and so far it ran for around 50 songs without a problem. 

However, I did not manage to reproduce the issue on my squeezelite clients because something else came up which frankly did not even let me get this far. I had this problem before occasionally but it got a lot worse today. Basically all my squeezeylite clients (recieving music from spotify) disconnect at the same time from the server and stop playback this way. It got so bad that it happened every 2 to 3 songs today. 

The logs kept on posting the following over and over every 30 seconds to one minute: 

2024-12-09 14:42:32.466 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/aioslimproto/cli.py", line 300, in _handle_jsonrpc_client
    cmd_result = await self._handle_command(command_msg["params"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/aioslimproto/cli.py", line 653, in _handle_command
    cmd_result = await cmd_result
                 ^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/aioslimproto/cli.py", line 808, in _handle_serverstatus
    if len(players) > limit:
       ^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'int' and 'str'

And then when the clients disconnected they showed this line for every client once.

2024-12-09 14:43:03.575 WARNING (MainThread) [aioslimproto.server.cli] No handler for alarms


The strange thing is, that the clients work fine with the stand-alone LMS add-on in homeassistant. I can play music through the home assistant play provider to the LMS add-on and I have not seen a single disconnect so far. Unfortunately, this method is also unusable because it only changes the song when I manually skip it and otherwise just repeats the song that is playing. 

I hope you can see something in this symptoms.because I really fail to see a system here. Thank you for your help.

**Comment by OzGav** [comment]
Why do you keep referring to LMS in your edit 2? Is that a typo?

**Comment by OzGav** [comment]
Also please don't post log excerpts. Restart MA. Get the problem to occur then download and attach the full log

**Comment by Haloto** [comment]
> Why do you keep referring to LMS in your edit 2? Is that a typo? I think maybe you are referring to your ESP squeezelite clients. If so please avoid using LMS as we think of the server in that case.

I was referring to the combination of using Spotify as a music provider and slimproto as a play provider with ESP squeelite clients.



> Also please don't post log excerpts. Restart MA. Get the problem to occur then download and attach the full log

Sorry, I thought it would be helpful to describe some other symtoms I was experiencing. Unfortunately the problems appear maybe every 30 minutes to and hour so it takes quite a lot of time to test different scenarios. Thats why I uploaded just the relevant parts when they appeared in my logs. Anyway please refere to my first post. It has the full logs concerning this specific issue.

**Comment by huwylphi** [comment]
I can report similar behavior using Spotify as music provider and slimproto as a play provider with a Squeezebox Boom device: my Spotify playlist is played until some track where at the end it jump some seconds back and play it again and again.
I also tried to:
1. enable the "force mp3" option: same result with suddenly one track endlessly repeating the end part.
2. stream to snapcast client browser tab: sometimes the playlist just stopped after some tracks but did not experienced one track endlessly repeating the end part.
3. create a universal player group and attached my Squeezebox Boom player: seems to be a workaround except that sometimes the playlist stops before the end (like when streaming to snapcast client browser tab)
4. also when attaching my Squeezebox Boom player to the group and physically powering off the Squeezebox device leads to the group not working at all once the player is back online (have to manually delete and recreate the group)

**Comment by OzGav** [comment]
@Haloto is this the problem discussed on discord that ended being a networking issue?

**Comment by OzGav** [comment]
In order for this to be fixed we need the problem isolated and repeatable. So please continue testing.

**Comment by Haloto** [comment]
Alright, here a preliminary update. I switched to a Pi for the last three days which is connected over the 5g network and it seems stable so far with zero disconnects from the server. However, i still cought it once timing out with a slightly different log "[ffmpeg.3953] No audio data received from source after timeout". Here are the logs: 
[Timeout.txt](https://github.com/user-attachments/files/18401422/Timeout.txt)

Since it is a slightly different log, do you think it is the same problem?

**Comment by marcelveldt** [comment]
Its the same issue - we're investigating it here https://github.com/music-assistant/support/issues/3257

**Comment by OzGav** [comment]
We have identified a problem with ffmpeg. An update has been shipped in 2.4.0b14. Please report if this has been fixed

**Comment by Haloto** [comment]
> Its the same issue - we're investigating it here #3257



> We have identified a problem with ffmpeg. An update has been shipped in 2.4.0b14. Please report if this has been fixed

Thank you very much to both of you. The work you do is amazing! :) 

I started testing now and will report how it goes.

**Comment by OzGav** [comment]
Thanks. Please now test with 2.4.0b15+

**Comment by Haloto** [comment]
Alright here an update after testing it for a while. Unfortunately I have to report, that the timout error still shows up for me. This time it seems to be able to continue playing, though. In the integration it is reported as changing to idle and then to playing in the same second. I had it running silently all day so I will have to see tomorrow how it actually sounds when this behaviour occurs., 

See the logs here: 

[Post Update Timeout.txt](https://github.com/user-attachments/files/18443431/Post.Update.Timeout.txt)

**Comment by OzGav** [comment]
beta 17 has been released with a fix for this. Please advise if this is resolved

**Comment by Haloto** [comment]
Unfortunately something seems to have gone wrong on my side. When i updated to beta 16 already the beta add on would refuse to start. The update to 17 did not fix that. I also tried reinstalling it but no change. The normal AddOn works, though. 

Here are the logs. Sorry I am on the pjone so i can only post it like that: 

`2025-01-18` 11:48:45.316 INFO (MainThread) [music_assistant] Starting Music Assistant Server (55748084e75b47b5b4cc9f02065169a7) version 2.4.0b17 - HA add-on: True - Safe mode: False
2025-01-18 11:48:45.419 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2025-01-18 11:48:45.608 INFO (MainThread) [music_assistant.music] Using a sync interval of 720 minutes.
2025-01-18 11:48:46.802 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/app/venv/lib/python3.12/site-packages/music_assistant/__main__.py", line 213, in start_mass
    await mass.start()
  File "/app/venv/lib/python3.12/site-packages/music_assistant/mass.py", line 175, in start
    await self.streams.setup(await self.config.get_core_config("streams"))
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/streams.py", line 207, in setup
    await check_ffmpeg_version()
  File "/app/venv/lib/python3.12/site-packages/music_assistant/helpers/ffmpeg.py", line 338, in check_ffmpeg_version
    version = output.decode().split("ffmpeg version ")[1].split(" ")[0].split("-")[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range``

**Comment by OzGav** [comment]
I would trying removing the beta and then install it again

**Comment by Haloto** [comment]
I tried twice and included the "delete all addon data" toggle and redtarted my home assistsnt servere twice aswell. No change and it still does not start. 

When i stop it it throws this error. Do you have idea how i can fix it? 

```
2025-01-18 13:13:56.386 WARNING (MainThread) [aiorun] Stopping the loop
2025-01-18 13:13:56.386 INFO (MainThread) [aiorun] Entering shutdown phase.
2025-01-18 13:13:56.387 INFO (MainThread) [aiorun] Executing provided shutdown_callback.
2025-01-18 13:13:56.387 INFO (MainThread) [root] shutdown requested!
2025-01-18 13:13:56.388 INFO (MainThread) [music_assistant] Stop called, cleaning up...
2025-01-18 13:13:56.390 INFO (MainThread) [aiorun] Waiting for executor shutdown.
2025-01-18 13:13:56.393 INFO (MainThread) [aiorun] Shutting down async generators
2025-01-18 13:13:56.394 INFO (MainThread) [aiorun] Closing the loop.
2025-01-18 13:13:56.394 INFO (MainThread) [aiorun] Leaving. Bye!
2025-01-18 13:13:56.395 INFO (MainThread) [aiorun] Reraising unhandled exception
2025-01-18 13:13:56.396 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "/app/venv/bin/mass", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/__main__.py", line 215, in main
    run(
  File "/app/venv/lib/python3.12/site-packages/aiorun.py", line 370, in run
    raise pending_exception_to_raise
  File "/app/venv/lib/python3.12/site-packages/aiorun.py", line 272, in run
    shutdown_callback(loop)
  File "/app/venv/lib/python3.12/site-packages/music_assistant/__main__.py", line 205, in on_shutdown
    loop.run_until_complete(mass.stop())
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/mass.py", line 199, in stop
    await self.streams.close()
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/streams.py", line 241, in close
    await self._server.close()
  File "/app/venv/lib/python3.12/site-packages/music_assistant/helpers/webserver.py", line 93, in close
    await self._tcp_site.stop()
          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'stop'
```

**Comment by OzGav** [comment]
Remove the addon completely
Restart HA
Add the beta addon but DO NOT start it.
Go to the configuration options for the addon and turn on SAFE MODE
Start the addon 
See what happens!

**Comment by Haloto** [comment]
Unfortunately it is the same behaviour. 

```
2025-01-20 10:27:33.422 INFO (MainThread) [music_assistant] Starting Music Assistant Server (0f3d5f82e7e246cc9e3686c6da3768f2) version 2.4.0b18 - HA add-on: True - Safe mode: True
2025-01-20 10:27:33.525 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2025-01-20 10:27:34.522 INFO (MainThread) [music_assistant.music] Using a sync interval of 720 minutes.
2025-01-20 10:27:35.641 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/app/venv/lib/python3.12/site-packages/music_assistant/__main__.py", line 213, in start_mass
    await mass.start()
  File "/app/venv/lib/python3.12/site-packages/music_assistant/mass.py", line 175, in start
    await self.streams.setup(await self.config.get_core_config("streams"))
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/streams.py", line 207, in setup
    await check_ffmpeg_version()
  File "/app/venv/lib/python3.12/site-packages/music_assistant/helpers/ffmpeg.py", line 338, in check_ffmpeg_version
    version = output.decode().split("ffmpeg version ")[1].split(" ")[0].split("-")[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by OzGav** [comment]
Are you out of RAM?

**Comment by OzGav** [comment]
Please confirm you have stopped the stable version of the server before trying to start the beta

**Comment by Haloto** [comment]
Yes I run HAOS bare metal on an old Acer Aspire One 725 and istalled music assistant (beta and stable) through the HA AddOn Store.

**Comment by OzGav** [comment]
I’m checking to see if the CPU is maybe incompatible with the changes made in beta 16

**Comment by Haloto** [comment]
Ok thank you very much. This might be (a very unfortunate) explanation.

**Comment by marcelveldt** [comment]
Yeah, that notebook has a rather limited (and old) CPU that lacks a number of modern instructions.
There is indeed a chance that this is just too old for the newer ffmpeg builds. I will add some more debug logging in the next beta to confirm that

**Comment by Haloto** [comment]
Ok thank you for looking into it. Please let me know if I can test something.

**Comment by OzGav** [comment]
Please try again with debug logging turned on in the addon config

**Comment by Haloto** [comment]
See the logs below. It still shows the same behaviour. 

[MA CPU test log.txt](https://github.com/user-attachments/files/18694216/MA.CPU.test.log.txt)

**Comment by OzGav** [comment]
Unfortunately, your CPU is incompatible with the MA requirements

**Comment by Haloto** [comment]
Well thats a shame but then I guess I will have to wait until I ugraded my HA Server. Who knows, maybe that is also going to help with my connectivity problems. Thank you very much for the help!!

**Comment by OzGav** [comment]
For future readers the following has been added to the documentation to provide some guidance as to the hardware requirements.

Recent 64 bit Intel CPU (max 10 years old, although 15 years may still work)
Recent AMD CPU (max 5 years old, although 10 years old may still work)
Single Board Computer: Raspberry Pi 4 or newer, or equivalent
Other aarch64 based CPU, supported by Home Assistant (e.g. Rockchip)
4 GB memory minimal if HAOS on the same machine
