### ISSUE TITLE
Cannot display/play albums or playlists on subsonic

### ISSUE THREAD

**Issue by olterman** [music-assistant/support#3337]
### What version of Music Assistant has the issue?

 2.3.4 

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I am using HA music assistant with subsonic as my only music provider ... since the update I can play individual tracks but I get no tracks showing up in albums or playlists, each time I try to load an album or playlist I get 'no playable items. 
`2024-12-21 08:08:21.291 ERROR (MainThread) [music_assistant.metadata] Error while updating metadata for library://playlist/6: Album 12340 not found`
I also get this error message in the log 
 `2024-12-21 08:08:02.033 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/tracks/get_track: OpenSonicProvider.get_album() got an unexpected keyword argument 'prov_ablum_id'`
 I have reinstalled the integration, cleaned cache, reinstalled the provider 

### How to reproduce

Clicking on any of the albums or playlist result in the album not found error message 

### Music Providers

subsonic

### Player Providers

snapcast

### Full log output

[
[d5369777_music_assistant_2024-12-21T07-13-51.686Z.log](https://github.com/user-attachments/files/18217649/d5369777_music_assistant_2024-12-21T07-13-51.686Z.log)
](url)

### What version of Home Assistant Core are your running

2024.12.5

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
@khers

**Comment by olterman** [comment]
`2024-12-22 21:31:26.655 ERROR (MainThread) [music_assistant.webserver] Error handling message: CommandMessage(message_id=99, command='music/playlists/playlist_tracks', args={'item_id': '75', 'provider_instance_id_or_domain': 'library', 'force_refresh': False})
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/opensubsonic/sonic_provider.py", line 514, in get_album
    sonic_album: SonicAlbum = await self._run_async(self._conn.getAlbum, prov_album_id)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/opensubsonic/sonic_provider.py", line 396, in _run_async
    return await self.mass.create_task(call, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/libopensonic/connection.py", line 1517, in getAlbum
    self._checkStatus(dres)
  File "/app/venv/lib/python3.12/site-packages/libopensonic/connection.py", line 2508, in _checkStatus
    raise exc(result['error']['message'])
libopensonic.errors.DataNotFoundError: Album not found.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/webserver.py", line 353, in _run_handler
    async for item in iterator:
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/media/playlists.py", line 66, in tracks
    tracks = await self._get_provider_playlist_tracks(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/media/playlists.py", line 364, in _get_provider_playlist_tracks
    items = await provider.get_playlist_tracks(item_id, page=page)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/opensubsonic/sonic_provider.py", line 627, in get_playlist_tracks
    album = await self._run_async(self.get_album, prov_album_id=sonic_song.parent)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/opensubsonic/sonic_provider.py", line 396, in _run_async
    return await self.mass.create_task(call, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/opensubsonic/sonic_provider.py", line 518, in get_album
    raise MediaNotFoundError(msg) from e
music_assistant_models.errors.MediaNotFoundError: Album 17459 not found`

**Comment by olterman** [comment]
I also tried a separate navidrome instnce to see if it was a subsonic issue, but get the same results...

**Comment by OzGav** [comment]
Can you rollback to 2.3.3 and check if it occurs there.

**Comment by amoranvalero** [comment]
Same issue here with 2.3.4 version. Only using subsonic server as music source. OpenSonicProvider.get_album() got an unexpected keyword argument 'prov_ablum_id' error just opening Music Assistant web interface. Blank interface display after displaying the error.
![error](https://github.com/user-attachments/assets/32791bb3-f124-4469-865a-f2478ad64837)

**Comment by OzGav** [comment]
Again rollback to 2.3.3 and see if it resolves.

**Comment by olterman** [comment]
I am sorry I am ussing the HA Addon ... how would I roll back an addon in homeassistant (appologise for my ignorance)

**Comment by OzGav** [comment]
By restoring the backup you made when you updated

**Comment by olterman** [comment]
@OzGav rolled back to 2.3.3 and I can again play my playlists and albums ... alla works except in HA when I click on Music assistant I get a 503 error

**Comment by olterman** [comment]
the 503 error resolved after clearing the browser cache ... so the issue is definately something that was changed in 2.3.4.

**Comment by OzGav** [comment]
@khers

**Comment by olterman** [comment]
Huh, I didnt't even spot that ... that sounds very plausible

**Comment by OzGav** [comment]
Well spotted. Will see if there is more to it than this https://github.com/music-assistant/server/pull/1818

**Comment by khers** [comment]
@mcfrojd good spot, that is a problem but possibly not the only problem. If this commit does not fix the issue then I  will need dig into how Navidrome represents its play list entries.

**Comment by codeinabox** [comment]
I am experiencing this problem too with Navidrome. I have downgraded the server to 2.7.7 in the interim

**Comment by OzGav** [comment]
Please confirm this has been fixed in 2.3.5

**Comment by olterman** [comment]
Confirmed
