### ISSUE TITLE
Unable to play specific Apple Music Track

### ISSUE THREAD

**Issue by chasut** [music-assistant/support#3372]
### What version of Music Assistant has the issue?

2.4.0b7

### What version of the Home Assistant Integration have you got installed?

Native integration from 2025.12.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Unable to play a specific track from the Apple Music provider.  Track is: 
Title: I've Seen All Good People: A. Your Move, B. All Good People
Artist: Yes
Album: The Yes Album 

### How to reproduce

Attempt to play this track from Apple Music Provider.

### Music Providers

Apple Music

### Player Providers

Airplay

### Full log output

[MASS_log.txt](https://github.com/user-attachments/files/18254359/MASS_log.txt)

### Additional information

Working on this new playlist and have been experiencing this for a while but not understanding what was happening until now.  The music just stops but presents as if it is still playing (the previous song).  Nothing in the logs. When I attempt to skip forward, the next song plays, but oddly, the queue thinks it is playing this song.  but the error "[music_assistant.webserver] Error handling message: players/cmd/next: 'songList'" then appears in the log.  I get the same error if I attempt to play the track directly.

I thought it might be the rather convoluted title, but the similarly titled "Starship Trooper: A. Life Seeker, B. Disillusion, C. Würm" has no problem.  There are longer and weirder titles in this playlist as well with no issue.

You should be able to test from this playlist at: https://music.apple.com/us/playlist/prog-rock/pl.u-5Lq1ytPMVRz

### What version of Home Assistant Core are your running

2024.12.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

macOS

**Comment by OzGav** [comment]
@MarvinSchenkel

**Comment by alfista2600** [comment]
following. new installation and I get AppleMusic search results, but every attempt to play a song results in a similar/same 'SongList' error referenced above (I think).

2024-12-31 18:45:43.140 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_media: 'songList'

**Comment by MarvinSchenkel** [comment]
Finally found some time to try and reproduce this issue, but not luck so far. Interestingly enough, I can play the track you mentioned when I search for it and play it straight from the search menu:

<img width="824" alt="image" src="https://github.com/user-attachments/assets/3978361c-4b17-46f4-a631-41ec7e82973b" />

However, I am on 2.4.0 BETA 8. Can you try and update and see if the issue persists?

**Comment by chasut** [comment]
I downgraded from 2.4.0b8 for another issue with it, but just upgraded and still get the error when attempting to play that song.  Tried both directly from the search as well as from the playlist with the same results.

Wondering if it has something to do with my account.  I am a long-time Apple Music user with a history of iTunes purchased music, as well as ripped cds, etc.  Also had their iTunes matching thing, but don't even know the status of that.  But then again I have played a lot of stuff in the MAS era without issues.  I completely cleaned out all of that from the local library.  Still very odd that it only happens for me on this one song. 

Turned on debug and have a little more to share:

`2025-01-03 13:39:32.791 DEBUG (MainThread) [music_assistant.players] Handling command cmd_play for player Home Audio
2025-01-03 13:39:32.793 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for library://track/943
2025-01-03 13:39:33.094 ERROR (MainThread) [music_assistant.webserver] Error handling message: CommandMessage(message_id=17, command='players/cmd/play_pause', args={'player_id': 'syncgroup_aqmqbbqz'})
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/players.py", line 89, in wrapper
    await func(self, *args, **kwargs)
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/players.py", line 203, in cmd_play
    await self.mass.player_queues.play(active_queue.queue_id)
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/player_queues.py", line 590, in play
    await self.resume(queue_id)
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/player_queues.py", line 715, in resume
    await self.play_index(queue_id, resume_item.queue_item_id, resume_pos, fade_in)
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/player_queues.py", line 766, in play_index
    queue_item.streamdetails = await get_stream_details(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/helpers/audio.py", line 230, in get_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(prov_media.item_id)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/apple_music/__init__.py", line 359, in get_stream_details
    stream_metadata = await self._fetch_song_stream_metadata(item_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/apple_music/__init__.py", line 722, in _fetch_song_stream_metadata
    return content["songList"][0]
           ~~~~~~~^^^^^^^^^^^^
KeyError: 'songList'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/webserver.py", line 361, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/players.py", line 260, in cmd_play_pause
    await self.cmd_play(player.player_id)
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/players.py", line 91, in wrapper
    raise PlayerCommandFailed(str(err)) from err
music_assistant_models.errors.PlayerCommandFailed: 'songList'`

**Comment by chasut** [comment]
Playing around a little bit.  If I play the song in the heading, I get the error (see first screenshot).  If I play the third track in the "other versions" list, it plays fine.  In the list, it looks to have the same artwork.  However, if you open more info on that particualar track it shows different artwork, and is clearly from a different album, etc.  Don't know if that is significant, but thought I would share.

BTW, I certainly have a good workaround for this, but happy to help you hunt this down as well.  If you cannot recreate it, then it is most likely specific to my setup.  But others may hit this as well.

Anyway, Thanks

<img width="1599" alt="Screenshot 2025-01-03 at 2 17 05 PM" src="https://github.com/user-attachments/assets/5a001f49-c1a1-4766-86a5-1c48e6d0604c" />

<img width="1598" alt="Screenshot 2025-01-03 at 2 17 34 PM" src="https://github.com/user-attachments/assets/36a5e7dd-2d99-43d2-80ea-f7cd0c1c003f" />

**Comment by chasut** [comment]
After updating to 2.4.0b16 the song I was having issues with played for the first time!  I didn't expect it to start working, but perhaps it was related to this ->[https://github.com/music-assistant/server/pull/1872](url).

The behavior was different (wouldn't play song at all vs. hanging at the end of a track).

But whatever the reason, I am no longer having this issue.  I confirmed it plays either directly from the track or from within the playlist.
